server {
    listen 80;
    server_name xmambos.com teladoshi.com ~^(?<tenant>.+)\\.xmambos\\.(local|com)$ ~^(?<tenant>.+)\\.teladoshi\\.(local|com)$ ~^(?<tenant>.+)\\..+$;

    resolver 127.0.0.11 8.8.8.8 valid=30s;

    # location /certificates/ {
    #     proxy_pass ${CERTIFICATES_URL}/; # Added trailing slash
    #     proxy_set_header Host $http_host; # Changed from $proxy_host
        
    #     proxy_ssl_server_name on;
    #     proxy_ssl_name $proxy_host;

    #     proxy_set_header X-Forwarded-Prefix /certificates;
        
    #     proxy_set_header X-Forwarded-Host $http_host;
    #     proxy_set_header X-Tenant $tenant;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }

    # location /remittance/ {
    #     proxy_pass ${REMITTANCE_URL}/; # Added trailing slash
    #     proxy_set_header Host $http_host; # Changed from $proxy_host
        
    #     proxy_ssl_server_name on;
    #     proxy_ssl_name $proxy_host;

    #     proxy_set_header X-Forwarded-Prefix /remittance;
        
    #     proxy_set_header X-Forwarded-Host $http_host;
    #     proxy_set_header X-Tenant $tenant;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }

    # location /tour/ {
    #     proxy_pass ${TOUR_URL}/; # Added trailing slash
    #     proxy_set_header Host $http_host; # Changed from $proxy_host
        
    #     proxy_ssl_server_name on;
    #     proxy_ssl_name $proxy_host;

    #     proxy_set_header X-Forwarded-Prefix /tour;
        
    #     proxy_set_header X-Forwarded-Host $http_host;
    #     proxy_set_header X-Tenant $tenant;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }

    location /cms/ {
        proxy_pass ${CMS_URL}/; # Added trailing slash
        proxy_set_header Host $http_host;
        
        proxy_ssl_server_name on;
        proxy_ssl_name $proxy_host;

        proxy_set_header X-Forwarded-Prefix /cms;

        
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Tenant $tenant;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass ${CMS_URL};
        proxy_set_header Host $http_host;
        
        proxy_ssl_server_name on;
        proxy_ssl_name $proxy_host;
        
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Tenant $tenant;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}