# Generated by Django 5.0 on 2026-05-15 00:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_pt', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(help_text='Main cover image', upload_to='services/covers/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('specialization', models.CharField(max_length=255)),
                ('specialization_pt', models.CharField(max_length=255, null=True)),
                ('specialization_en', models.CharField(max_length=255, null=True)),
                ('badge_tags', models.CharField(max_length=255)),
                ('mastery_text', models.TextField()),
                ('mastery_text_pt', models.TextField(null=True)),
                ('mastery_text_en', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_pt', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(help_text='Main cover image', upload_to='services/covers/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=50)),
                ('engine', models.CharField(max_length=100)),
                ('features', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_pt', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(help_text='Main cover image', upload_to='services/covers/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(max_length=255)),
                ('subtitle_pt', models.CharField(max_length=255, null=True)),
                ('subtitle_en', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('location_pt', models.CharField(max_length=255, null=True)),
                ('location_en', models.CharField(max_length=255, null=True)),
                ('opening_hours', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_pt', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(help_text='Main cover image', upload_to='services/covers/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('category_pt', models.CharField(max_length=100, null=True)),
                ('category_en', models.CharField(max_length=100, null=True)),
                ('location_detail', models.CharField(max_length=255)),
                ('location_detail_pt', models.CharField(max_length=255, null=True)),
                ('location_detail_en', models.CharField(max_length=255, null=True)),
                ('amenities', models.TextField()),
                ('amenities_pt', models.TextField(null=True)),
                ('amenities_en', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='SEO friendly description', max_length=255)),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='teladoshi.expedition')),
                ('fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='teladoshi.fleet')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='teladoshi.restaurant')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='teladoshi.stay')),
            ],
        ),
        migrations.CreateModel(
            name='GuestStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('content_pt', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('rating', models.IntegerField(default=5)),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='teladoshi.expedition')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='teladoshi.restaurant')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='teladoshi.stay')),
            ],
        ),
        migrations.CreateModel(
            name='Stopover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_pt', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_pt', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(help_text='Main cover image', upload_to='services/covers/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('arrival_city', models.CharField(default='Lisbon', max_length=100)),
                ('pricing_guide_json', models.JSONField(help_text='Store 1-4 passengers, 5-8 passengers rates')),
                ('transfer_details', models.TextField()),
                ('transfer_details_pt', models.TextField(null=True)),
                ('transfer_details_en', models.TextField(null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='teladoshi.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stay',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='teladoshi.vendor'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='teladoshi.vendor'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_pt', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_pt', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(help_text='Main cover image', upload_to='services/covers/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('access_type', models.CharField(default='Free Access', max_length=100)),
                ('coordinates', models.CharField(blank=True, max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='teladoshi.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fleet',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='teladoshi.vendor'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_services', to='teladoshi.vendor'),
        ),
    ]
