# Generated by Django 5.0 on 2026-05-15 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teladoshi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='teladoshi.place'),
        ),
    ]
