# Generated by Django 5.0 on 2026-05-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('teladoshi', '0002_serviceimage_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimage',
            name='expedition',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='fleet',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='place',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='stay',
        ),
        migrations.AddField(
            model_name='expedition',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expedition',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='name_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stopover',
            name='pricing_guide_json',
            field=models.JSONField(help_text='Store passenger group rates'),
        ),
        migrations.DeleteModel(
            name='GuestStory',
        ),
    ]
